### ISSUE TITLE
import in Visual Studio gives error string of null

### ISSUE THREAD

**Issue by conjordan** [cinder92/react-native-circular-menu#6]
Hello,

I'm not sure what I'm doing wrong but following your instructions I added the package to my Windows 10 application per npm and imported it, when I start it fails immediately at the import statement giving me string is null. I am using Visual Studio 2017 and running the app through powershell with react-native run-windows

Thx for your help.

**Comment by cinder92** [comment]
Hello there, this component, is not going to work on react native windows, just iOS and Android

**Comment by conjordan** [comment]
Okay, the entry at JSCoach is wrong https://js.coach/react-native-circular-menu?search=circular it says works with windows.
