### ISSUE TITLE
Add a dependency on prop-types

### ISSUE THREAD

**Issue by manurana** [cinder92/react-native-circular-menu#7]
Currently it is assumed that the `prop-types` package is part of the parent project. In the absence of this package, an error is thrown while defining `CircularMenu.propTypes`

This dependency needs to be explicitly added to `package.json`

**Comment by manurana** [comment]
Sorry, a PR is already in place for this

**Comment by Razorholt** [comment]
What's the fix? I'm getting the PropTypes error. Thanks!

**Comment by mateus4k** [comment]
@Razorholt the fix is ​​to install `prop-types` from the npm repo and import into `index.js`.

**Comment by cinder92** [comment]
Fixed
